"use strict";

var new_game = new ticTacToe("X");

// Game Over stuff tests
console.log("Game over tests");
console.log("Blank:",new_game.game_over(Array("-", "-", "-", "-", "-", "-", "-", "-", "-")) === false);
console.log("Top Row X:",new_game.game_over(Array("X", "X", "X", "-", "-", "-", "-", "-", "-")) === true);
console.log("Mid Row X:",new_game.game_over(Array("-", "-", "-", "X", "X", "X", "-", "-", "-")) === true);
console.log("Bot Row X:",new_game.game_over(Array("-", "-", "-", "-", "-", "-", "X", "X", "X")) === true);
console.log("Top Row O:",new_game.game_over(Array("O", "O", "O", "-", "-", "-", "-", "-", "-")) === true);
console.log("Mid Row O:",new_game.game_over(Array("-", "-", "-", "O", "O", "O", "-", "-", "-")) === true);
console.log("Bot Row O:",new_game.game_over(Array("-", "-","-","-","-","-","O", "O", "O")) === true);
console.log("Lef Dia X:",new_game.game_over(Array("X", "-","-","-","X","-","-", "-", "X")) === true);
console.log("Lef Dia O:",new_game.game_over(Array("O", "-","-","-","O","-","-", "-", "O")) === true);
console.log("Rig Dia X:",new_game.game_over(Array("-", "-","X","-","X","-","X", "-", "-")) === true);
console.log("Rig Dia O:",new_game.game_over(Array("-", "-","O","-","O","-","O", "-", "-")) === true);
console.log("Lef Dow X:",new_game.game_over(Array("X", "-","-","X","-","-","X", "-", "-")) === true);
console.log("Lef Dow O:",new_game.game_over(Array("O", "-","-","O","-","-","O", "-", "-")) === true);
console.log("Mid Dow X:",new_game.game_over(Array("-", "X","-","-","X","-","-", "X", "-")) === true);
console.log("Mid Dow O:",new_game.game_over(Array("-", "O","-","-","O","-","-", "O", "-")) === true);
console.log("Rig Dow X:",new_game.game_over(Array("-", "-","X","-","-","X","-", "-", "X")) === true);
console.log("Rig Dow O:",new_game.game_over(Array("-", "-", "O", "-", "-", "O", "-", "-", "O")) === true);
console.log("Blank:",new_game.game_over(Array("-", "X", "-", "O", "-", "-", "X"," -", "-")) === false);
console.log("Blank:",new_game.game_over(Array("-", "-","-","-","-","-","-","-","-")) === false);
console.log("Issue1:",new_game.game_over(Array("O", "-", "-", "-", "X", "-", "-", "-", "X"))===false);
console.log("Issue2:",new_game.game_over(Array("X", "X", "O", "-", "O", "-", "-", "X", "-"))===false);
console.log("Issue4:", new_game.game_over(Array("X", "X", "O", "-", "O", "-", "O", "X", "-"))===true);
console.log("Issue6:",new_game.game_over(Array("X", "X", "O", "O", "O", "X", "-", "X", "-"))===false);
console.log("Issue7:",new_game.game_over(Array("O", "X", "-", "X", "X", "O", "X", "O", "-"))===false);
console.log("Rate Board tests");
console.log("Test1",new_game.rate_move(Array("-","-","-","-","-","-","-","-","-"),0) === 0);
console.log("Test2",new_game.rate_move(Array("X","X","X","-","-","-","-","-","-"),0) === -10);
console.log("Test3",new_game.rate_move(Array("-","-","-","X","X","X","-","-","-"),0) === -10);
console.log("Test4",new_game.rate_move(Array("-","-","-","-","-","-","X","X","X"),0) === -10);
console.log("Test5",new_game.rate_move(Array("O","O","O","-","-","-","-","-","-"),0) === 10);
console.log("Test6",new_game.rate_move(Array("-","-","-","O","O","O","-","-","-"),0) === 10);
console.log("Test7",new_game.rate_move(Array("-","-","-","-","-","-","O","O","O"),0) === 10);
console.log("Test8",new_game.rate_move(Array("X","-","-","-","X","-","-","-","X"),0) === -10);
console.log("Test9",new_game.rate_move(Array("O","-","-","-","O","-","-","-","O"),0) === 10);
console.log("Test10",new_game.rate_move(Array("-","-","X","-","X","-","X","-","-"),0) === -10);
console.log("Test11",new_game.rate_move(Array("-","-","O","-","O","-","O","-","-"),0) === 10);
console.log("Test12",new_game.rate_move(Array("X","-","-","X","-","-","X","-","-"),0) === -10);
console.log("Test13",new_game.rate_move(Array("O","-","-","O","-","-","O","-","-"),0) === 10);
console.log("Test14",new_game.rate_move(Array("-","X","-","-","X","-","-","X","-"),0) === -10);
console.log("Test15",new_game.rate_move(Array("-","O","-","-","O","-","-","O","-"),0) === 10);
console.log("Test16",new_game.rate_move(Array("-","-","X","-","-","X","-","-","X"),0) === -10);
console.log("Test17",new_game.rate_move(Array("-","-","O","-","-","O","-","-","O"),0) === 10);
console.log("Test18",new_game.rate_move(Array("-","X","-","O","-","-","X","-","-"),0) === 0);
console.log("Test19",new_game.rate_move(Array("-","-","-","-","-","-","-","-","-"),0) === 0);
console.log("Issue1:",new_game.rate_move(Array("O", "-", "-", "-", "X", "-", "-", "-", "X"),0)===0);
console.log("Issue2:",new_game.rate_move(Array("X", "X", "O", "-", "O", "-", "-", "X", "-"),0)===0);
console.log("Issue3:",new_game.rate_move(Array("X", "X", "O", "O", "O", "-", "-", "X", "-"),0)===0);
console.log("Issue4:", new_game.rate_move(Array("X", "X", "O", "-", "O", "-", "O", "X", "-"),0)===10);
console.log("Issue5:",new_game.rate_move(Array("X", "X", "O", "O", "O", "-", "-", "X", "-"),0)===0);
console.log("Issue6:",new_game.rate_move(Array("X", "X", "O", "O", "O", "X", "-", "X", "-"),0)===0);
console.log("Issue7:",new_game.rate_move(Array("O", "X", "X", "X", "O", "O", "O", "X", "X"),0));
console.log("MINIMAX TESTS");
console.log("EASY WIN",new_game.maximised_move(Array("X", "X", "O", "-", "O", "-", "-", "X", "-"), 0));
console.log("EASY 2",new_game.maximised_move(Array("-", "X", "X", "-", "O", "O", "O", "X", "X"), 0));
